package dxvfix.update;

import java.io.IOException;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.nio.charset.StandardCharsets;
import java.time.Duration;
import java.util.ArrayList;
import java.util.List;

/**
 * One entry in the repo's {@code versions.txt} -- a version the "Update version" feature can
 * offer, fetched from GitHub at runtime. The file is a plain pipe-delimited text format
 * (deliberately not JSON) because it's meant to be hand-edited directly by whoever maintains the
 * project, not generated by tooling: {@code version|releaseTag|available|notes} per line, "#"
 * comments and blank lines ignored. See versions.txt itself (repo root) for the full format
 * description.
 */
public final class VersionManifest {

    public static final String MANIFEST_URL =
            "https://raw.githubusercontent.com/SergioPimonno/dxvfix/main/versions.txt";
    private static final String DOWNLOAD_URL_TEMPLATE =
            "https://github.com/SergioPimonno/dxvfix/releases/download/%s/dxvfix.jar";

    public final String version;
    public final String releaseTag;
    public final boolean available;
    public final String notes;

    public VersionManifest(String version, String releaseTag, boolean available, String notes) {
        this.version = version;
        this.releaseTag = releaseTag;
        this.available = available;
        this.notes = notes;
    }

    /** The GitHub Release asset URL this version's dxvfix.jar is expected to be attached at. */
    public String downloadUrl() {
        return String.format(DOWNLOAD_URL_TEMPLATE, releaseTag);
    }

    @Override
    public String toString() {
        return notes == null || notes.isBlank() ? version : version + " -- " + notes;
    }

    /** Fetches versions.txt from GitHub and returns only the entries marked available. */
    public static List<VersionManifest> fetchAvailable() throws IOException, InterruptedException {
        List<VersionManifest> available = new ArrayList<>();
        for (VersionManifest v : parse(fetchRaw())) {
            if (v.available) available.add(v);
        }
        return available;
    }

    private static String fetchRaw() throws IOException, InterruptedException {
        HttpClient client = HttpClient.newBuilder()
                .connectTimeout(Duration.ofSeconds(15))
                .followRedirects(HttpClient.Redirect.NORMAL)
                .build();
        HttpRequest request = HttpRequest.newBuilder(URI.create(MANIFEST_URL))
                .timeout(Duration.ofSeconds(15))
                .GET()
                .build();
        HttpResponse<String> response = client.send(request, HttpResponse.BodyHandlers.ofString(StandardCharsets.UTF_8));
        if (response.statusCode() / 100 != 2) {
            throw new IOException("Failed to fetch version list: HTTP " + response.statusCode());
        }
        return response.body();
    }

    /** Parses the versions.txt text format. Public so it's directly unit-testable. */
    public static List<VersionManifest> parse(String text) {
        List<VersionManifest> result = new ArrayList<>();
        for (String line : text.split("\n", -1)) {
            String trimmed = line.strip();
            if (trimmed.isEmpty() || trimmed.startsWith("#")) continue;
            String[] parts = trimmed.split("\\|", -1);
            if (parts.length < 3) continue; // malformed line -- skip rather than fail the whole fetch
            String version = parts[0].strip();
            String releaseTag = parts[1].strip();
            boolean available = parts[2].strip().equalsIgnoreCase("yes");
            String notes = parts.length > 3 ? parts[3].strip() : "";
            if (version.isEmpty() || releaseTag.isEmpty()) continue;
            result.add(new VersionManifest(version, releaseTag, available, notes));
        }
        return result;
    }
}
